import { getPages } from '@/sanity/sanity-utils'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Colin Personal Website',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

// get all of our pages
const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        
        <header className="flex items-center justify-between">
          <Link 
            href="/" 
            className="bg-gradient-to-r via-red-500 from-orange-200 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >Colin</Link>

          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                {page.title}
              </Link>
            ))}
          </div>

        </header>

        <main className="py-20">
          {children}  
        </main>  
        
        
      </body>
    </html>
  )
}
